Added acquire lease method
Dome9/Python_API_SDK pull request #16
Opened 2019-09-15 11:42 UTC by erezbo

2019-09-15 12:01 UTC, paveli-d9 requested changes

2019-09-15 12:01 UTC, paveli-d9 commented on dome9ApiV2Py/dome9ApiV2Py.py
> +	def acquireAwsLease(self, cloudAccountId, securityGroupId, ip, portFrom, portTo=None, protocol='ALL', length='1:0:0', region=None, accountId=None, name=None, outAsJson=False):
Use none

2019-09-15 12:01 UTC, paveli-d9 commented on dome9ApiV2Py/dome9ApiV2Py.py
> +		data = {key: temp_data[key] for key in temp_data if temp_data[key] is not None}
data = {key: value for key, value in temp_data if value is not None}

2019-09-15 17:33 UTC, uditamar requested changes
@erezbo please squash

2019-09-15 19:18 UTC, paveli-d9 reviewed
@udidome9 LGTM, are you done with the review?

2019-09-15 19:39 UTC, uditamar requested changes
please squash

2019-09-18 07:11 UTC, erezweinstein5-zz approved these changes

2019-09-18 18:26 UTC, paveli-d9 requested changes
Please rewrite commit message:
1. Capitalize the headline.
2. Use imperative language.
3. Clean lines which describe temporary minor fixes
4. Write a short documentation for new API.

2019-09-19 07:06 UTC, paveli-d9 approved these changes

2019-09-19 07:08 UTC, merged